### ISSUE TITLE
Error: No images of the specified format were found

### ISSUE THREAD

**Issue by zyffse** [Transportation-Inspection/visual_odometry#1]
Thanks for your excellent work, when I run the code, I got the error like this:

Failed to load OpenCL runtime
Error: No images of the specified format were found. Verify the format in the CameraParams.txt

I kept the KITTI_smaple folder and CameraParams.txt in the src folder. Please help me how to fix this error. Thank you very much.

**Comment by jahdiel** [comment]
Hi, thanks for trying out the project and posting up the issue. Try cloning or downloading the repository again and everything should work out. If it doesn't let me in order to fix anything else. Thanks

**Comment by zyffse** [comment]
I am very thankful for your attention, but I am sorry to say I still have the same error even try it again and again.
Failed to load OpenCL runtime
Error: No images of the specified format were found. Verify the format in the CameraParams.txt
My Python is 2.7.6 and opencv version is 3.0.0-alpha, do you is this the problem?
Thank you very much.

**Comment by jahdiel** [comment]
Are you using linux? Also, do you have the opencv_contrib module installed into your Opencv? The project is tested on the OpenCV-dev, which is taken directly from Github, and it is compiled with opencv_contrib module, https://github.com/opencv/opencv_contrib.

**Comment by zyffse** [comment]
Tnahk you very much for your update and reply. I am using ubuntu 14.04 OS, and I have reinstalled the same version of OpenCV-dev 3.1.0 and open_contrib, and have tried by using the sample code form Opencv.org. It worked well. So I think there is no problem about opencv.
But  I still got the error when using your code.
The error is Error: No images of the specified format were found. Verify the format in the CameraParams.txt
Do you have any suggestion about that? Please help me, Thank you very much.

**Comment by jahdiel** [comment]
Hi, I have updated the code so that more exception messages are raised in order to find the exact source of the error. You might want to pull the latest edits. The message you are receiving is sent out when the images cannot be retrieved, therefore you might want to verify that the images are in the folder it is specified and that the image format is specified correctly, in the sample case it should be 'PNG'. Also, make sure you don't change any spacing in the CameraParams text file because it will produce errors. 

Also, try this as a simple hack to see if it works:

Find this line in the CameraParams_Parser.py (line 70 on the latest commit)
`self.images = glob.glob(self.folder + '/*.' + self.format)`
and change the forward slash to backslash
`self.images = glob.glob(self.folder + '\*.' + self.format)`

If non of it works keep me noted. Thanks for helping to better this project. 
Thank you very much.

**Comment by zyffse** [comment]
Thanks very much about your help.
I have download the latest edits, and modified the line 70 just like you mentioned. There is a new error:

leon@leon-Prime-Series:~/mvo_ml/src$ python MAIN.py CameraParams.txt
-- Press ESC key to end program
Traceback (most recent call last):
  File "MAIN.py", line 179, in <module>
    run()
  File "MAIN.py", line 50, in run
    CP = Cam_Parser.CameraParams(args.txt_file)
  File "/home/leon/mvo_ml/src/CameraParams_Parser.py", line 75, in **init**
    raise IOError('No such file or directory found - ' + self.txt[idx].strip())
IOError: No such file or directory found - KITTI_sample\images

Still working on this, hope you can help me. Thanks again.

**Comment by jahdiel** [comment]
Perfect, for know just change in the CamParams.txt file from:
`KITTI_sample\images`
to 
`KITTI_sample/images`

As always let me know of any problem.

**Comment by zyffse** [comment]
Jahdiel, Thank you so much. I have changed KITTI_sample\images to KITTI_sample/images in CamParams.txt. Then I got this:

len@leon:~/mvo_ml/src$ python MAIN.py CameraParams.txt
-- Press ESC key to end program

Traceback (most recent call last):
  File "MAIN.py", line 179, in <module>
    run()
  File "MAIN.py", line 50, in run
    CP = Cam_Parser.CameraParams(args.txt_file)
  File "/home/leon/mvo_ml/src/CameraParams_Parser.py", line 76, in **init**
    raise TypeError('No images of the specified format were found. Verify format in the CameraParams.txt')
TypeError: No images of the specified format were found. Verify format in the CameraParams.txt

Please help me to fix it, Thanks again.

**Comment by jahdiel** [comment]
Make sure line 68-70 in CameraParams_Parser.py is as follows:

`self.format = self.txt[idx+1].strip()`
`print self.folder + '/*.' + self.format`
`self.images = glob.glob(self.folder + '/*.' + self.format)` 

Add the print line and make sure the filepath given is the one in which the images are stored. And verify there is no anomaly to the default Linux format. Let me know what happens.

**Comment by zyffse** [comment]
Sorry so the late reply. I have tried a lot ways in the last week. Unfortunately, still the same error. 
With the "print", the images filepath is no problem.  
leon@leon-Prime-Series:~$ cd '/home/leon/mvo_ml/src' 
leon@leon-Prime-Series:~/mvo_ml/src$ python MAIN.py CameraParams.txt
-- Press ESC key to end program

KITTI_sample/images/*.PNG
Traceback (most recent call last):
  File "MAIN.py", line 179, in <module>
    run()
  File "MAIN.py", line 50, in run
    CP = Cam_Parser.CameraParams(args.txt_file)
  File "/home/leon/mvo_ml/src/CameraParams_Parser.py", line 77, in __init__
    raise TypeError('No images of the specified format were found. Verify format in the CameraParams.txt')
TypeError: No images of the specified format were found. Verify format in the CameraParams.txt

Thank you very much

**Comment by chienerh** [comment]
In my case, in Linux, changing the directory and the format in CameraParams.txt works.

KITTI_sample\images -> KITTI_sample/images
PNG -> png
KITTI_sample\poses.txt -> KITTI_sample/poses.txt

**Comment by ouyangandy** [comment]
PNG------png

**Comment by iSIlya** [comment]
@zyffse Have you been able to solve this problem? I faced the same problem.
